config/routes.rb
Comments::Engine.routes.draw do
  resources :comments
  root :to => 'comments#index'

end

app/models/comments/comment.rb
module Comments
    class Comment < ::ActiveRecord::Base
      attr_accessible :author, :content
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments/application_controller.rb
class Comments::ApplicationController < ActionController::Base
  protect_from_forgery
  layout "lcomment"
end

app/controllers/comments/comments_controller.rb
module Comments
    class CommentsController < ApplicationController
      def index
        @comments = Comment.all
      end
      
      def new
        @comment = Comment.new
      end
      
      def create
        @comment = Comment.new(params[:comment])
        if @comment.save
          flash[:notice] = "Successfully created comment."
          redirect_to comments_path
        else
          render :action => 'new'
        end
      end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments/application_helper.rb
module Comments::ApplicationHelper
end

app/views/comments/comments/_form.html.erb
<%= form_for @comment do |f| %>

  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/comments/index.html.erb
<h1> Comments </h1>

<table>
  <tr>
    <th>Author</th>
    <th>Content</th>
  </tr>
  <% for comment in @comments %>
    <tr>
      <td><%= comment.author %></td>
      <td><%= comment.content %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Comment", new_comment_path %></p>

app/views/comments/comments/new.html.erb
<h1> New Comment </h1>

<%= render 'form' %>

<p><%= link_to "Back to List", comments_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comments</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/lcomment.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cOMMENTS</title>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>